name: grabbing streams

on:
  schedule:
    - cron: '0 */1 * * *'


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"


      - name: grab m3u files
        run: |
            pwd
            cd ./core/platforms/
            python3 twitch.py altertvcy > ../../streams/ALTER_CY.m3u8     
            python3 twitch.py aktinaradio > ../../streams/AKTINA_RADIO.m3u8
            python3 twitch.py alithiavideo > ../../streams/ALITHIA_TV.m3u8
            python3 twitch.py radiotvanemosgr > ../../streams/ANEMOS_RADIO.m3u8
            python3 twitch.py astratv2021 > ../../streams/ASTRA_TV.m3u8
            python3 twitch.py astratv2019 > ../../streams/ASTRA_TV_2.m3u8
            python3 twitch.py chanialivetv > ../../streams/CHANIA_TV.m3u8
            python3 twitch.py diavata_tv > ../../streams/DIABATA_TV.m3u8
            python3 twitch.py dtpylias > ../../streams/DTP.m3u8
            python3 twitch.py failarmy > ../../streams/FAILARMY.m3u8
            python3 twitch.py farostv1959 > ../../streams/FAROS_TV_EKKLISIA.m3u8
            python3 twitch.py fatsabooktv > ../../streams/FATSABOOK_TV.m3u8
            python3 twitch.py younowflashtv > ../../streams/FLASH_TV.m3u8
            python3 twitch.py hotbeatstv > ../../streams/HOTBEAST_TV.m3u8
            python3 twitch.py iviewtvgr  > ../../streams/IVIEW_TV.m3u8
            python3 twitch.py konitsaplustv > ../../streams/KONITSA_TV.m3u8
            python3 twitch.py radiomakedonia > ../../streams/MAKEDONIA_RADIO.m3u8
            python3 twitch.py oloutheradio > ../../streams/OLOUTHE_RADIO.m3u8
            python3 twitch.py orthodoxiaradio > ../../streams/ORTHODOXIA_TV.m3u8
            python3 twitch.py pakoestream > ../../streams/PAKOE_TV.m3u8
            python3 twitch.py zefstv1 > ../../streams/PLUTON_TV.m3u8
            python3 twitch.py midnightsumo > ../../streams/SUMO.m3u8
            python3 twitch.py xtvision > ../../streams/XTVISION.m3u8
            python3 twitch.py xtvision2 > ../../streams/XTVISION_2.m3u8
            python3 dailymotion.py x2j7kha > ../../streams/Euronews_Greece.m3u8
            python3 dailymotion.py x8p5u0u > ../../streams/CGTN_Europe.m3u8
            python3 dailymotion.py x3b68jn > ../../streams/CNEWS.m3u8
            python3 dailymotion.py k5Hfx6eeaTjBE5zRXcn > ../../streams/STAR_KENTRIKHS_ELLADAS.m3u8
            python3 dailymotion.py 1ilp5b3jja3168a4092 > ../../streams/STAR_KENTRIKHS_ELLADAS_2.m3u8
            
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "streams updated"
          git push
